#### Library for scientific computing in Python. Supports arrays and matrices. along with a collection of mathematical functions

In [3]:
!pip install numpy

In [7]:
import numpy as np 

# Create arrays using numpy

## creating 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [25]:
arr2 = np.array([1,2,3,4,5,6])
print(arr2.reshape(2,3))
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
arr3 = np.array([1,2,3,4,5])
print(arr3.reshape(1,5)) # 1 row and 5 columns
print(arr3.shape)

[[1 2 3 4 5]]
(5,)


In [14]:
arr4 = np.array([[1,2,3,4,5]])
arr4.shape

(1, 5)

In [ ]:
## 2D Array
arr5 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr5)
arr5.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [31]:
np.arange(0,10, 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
## crate identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape) 
print("Number of dimensions:", arr.ndim) 
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)  # (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [37]:
## Numpy Vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Elementwise addition 
print('Addition:', arr1 + arr2)

## Elementwise substraction
print('Substraction: ', arr1 - arr2)

## Elementwise multiplication
print('Substraction: ', arr1 * arr2)

## Elementwise division
print('Substraction: ', arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Substraction:  [ 10  40  90 160 250]
Substraction:  [0.1 0.1 0.1 0.1 0.1]


In [40]:
## Universal Function

arr = np.array([4, 9, 16, 25])

## sq root
print(np.sqrt(arr))

## Exponential 
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[2. 3. 4. 5.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]
[-0.7568025   0.41211849 -0.28790332 -0.13235175]
[1.38629436 2.19722458 2.77258872 3.21887582]


In [44]:
## Array slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Array: \n', arr)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
arr[[0][0]]

array([1, 2, 3, 4])

In [46]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [48]:
arr[0:2, 2:]

array([[3, 4],
       [7, 8]])

In [49]:
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [50]:
## Modify array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [51]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [52]:
## Statistical concept --  Normalization
## Change data to have a mean of 0 and std of 1

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [53]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [61]:
## Logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])